### ISSUE TITLE
Duplicate detections

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#72] opened 2020-10-06 15:11 UTC
For 2013_albertkanaal, I noticed 1044 detections with the same primary key, e.g. `116645917`. They seem to be full duplicates (info in all fields is the same). @fwaumans can you verify this is actually how they occur in the database and remove the duplicates?

**Comment by peterdesmet** [comment] 2020-10-26 16:26
I also noticed 27782 duplicate detections for `2015_phd_verhelst_cod`. I am removing those when downloading, but I wonder if they should be removed from the database as well?

**Comment by jreubens** [comment] 2020-10-27 06:21
Can you provide me an overview of the duplicates. Then I can check how this is possible.

**Comment by peterdesmet** [comment] 2020-10-27 10:36
@jreubens attached, the 27782*2 duplicates in `2015_phd_verhelst_cod`: [2015_phd_verhelst_cod_dup_detections.txt](https://github.com/inbo/etn-occurrences/files/5444634/2015_phd_verhelst_cod_dup_detections.txt)

**Comment by fwaumans** [comment] 2020-11-01 22:31
I checked the detection with id_pk 116645917. The reason for the duplication are two 'different' animals (id_pk =524, 525)  in the in database which are released on the same data ("2015-04-22 00:00:00")  with the same tag (id_pk =618).
The problem is situated in the animal table. This is also the case for the other 1043 detections of the same tag. You have to delete or change one of the animal records.

**Comment by fwaumans** [comment] 2020-11-01 22:56
Same problem for the 27782 dupllicated detections: two animals released with the same tag.
Tags: id_pk = 502
Animals: id_pk = 2821, 628

**Comment by peterdesmet** [comment] 2020-11-02 19:13
Thanks for investigating @fwaumans. I have created two new issues regarding these supposed duplicated animals and assigned these to @PieterjanVerhelst to investigate. Once resolved (and the duplicates disappear) I will close this issue.

**Closed as completed** 2020-11-09 14:56 UTC
Labels: bug, etn data update, datapaper
